POST http://localhost:3001/api/notes
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmcxMjMiLCJpZCI6IjY2ODJlNTQ4OTZjODE3Njk4OGZiNDdkMyIsImlhdCI6MTcyMjg4NzEzNCwiZXhwIjoxNzIyODkwNzM0fQ.nS3VFIQhXXUWx2yF6-WRrpDgeafR2kSQyvK-djw54Fs

{
  "content": "auth note",
  "important": true,
  "userId": "65d39b3ef2a07197f8339db4"
}
###